### ISSUE TITLE
are 3d joint coordinates normalised in tf record files?

### ISSUE THREAD

**Issue by SuhelNaryal** [m-zayan/Large-scale-Multiview-3D-Hand-Pose#3]
Hi, are the 3d coordinates normalised in tf record file? Thank you.

**Comment by m-zayan** [comment]
No, but  you can easily apply any kind of transformation you want, you could check cells  12, 13 on the [notebook](https://github.com/m-zayan/large-scale-multiview-3d-hand-pose/blob/main/models/Bounding%20Box%20Estimation%20-%20Baseline%20Model/hand-tracking-bounding-box-estimation-tpu.ipynb).

```
features = {'image': _bytes_feature, 
            'bbox': _bytes_feature,
            'poses_2d': _bytes_feature,
            'poses_3d': _bytes_feature,
            'world_joints': _bytes_feature,
            'source_camera': _int64_feature}
```

`poses_3d`, represents - image plane

**Comment by SuhelNaryal** [comment]
Okay, Thanks. One more thing, Are the coordinates in tf records mapped into 512x512 space or not?

**Comment by m-zayan** [comment]
Only bounding boxes have been rescaled on TFRecords, you could rescale poses, following the same approach.

```
def decode_arr(resized_shape=None):
  
  scale_x, scale_y = 1.0, 1.0
    
  if resized_shape is not None:

    scale_x *= (resized_shape[1] / 640.0)
    scale_y *= (resized_shape[0] / 480.0)

  def fix_resized(bytes_str):

    arr = tf.io.decode_raw(bytes_str, out_type='float64')

    arr[:, 0] *= scale_x
    arr[:, 1] *= scale_y

    return arr
  
  return fix_resized
```

--------------------------

```
feature_dtype = {'image': 'bytes', 'poses_3d': 'bytes'}

processing_func = {'image': lambda x: x / 255.0, 'poses_3d': decode_arr(resized_shape=(512, 512))}

reader = TfRecordReader(features_dtype=feature_dtype, 
                        image_key='image', 
                        tfrecord_shape=(512, 512, 3), 
                        shape=None, 
                        channels=3, 
                        func=processing_func)
```

**Comment by SuhelNaryal** [comment]
okay, Thank you so much.

**Comment by SuhelNaryal** [comment]
@m-zayan Hi, I am trying to use this dataset in kaggle kernel on tpu but I am getting following error.

ServiceException: 401 Anonymous caller does not have storage.objects.list access to the Google Cloud Storage bucket.

Can you guide me through the error?

**Comment by m-zayan** [comment]
[TPUs with Private Datasets](https://www.kaggle.com/product-feedback/163416). 

If you are facing any types of errors while using kaggle it's better for you to ask on the [kaggle-discussion](https://www.kaggle.com/questions-and-answers)

**Comment by SuhelNaryal** [comment]
Thanks
